### ISSUE TITLE
Error 500 en configuracion de Woocommerce [Resuelto]

### ISSUE THREAD

**Issue by reandimo** [TransbankDevelopers/transbank-plugin-woocommerce-webpay#17]
Buen dia amigos, instale el plugin en mi ecommerce y al hacerlo no me deja acceder a la pagina de configuracion de woocommerce. Al desinstalarlo funciona perfecto es solo con este plugin, no se si pueda ser una incopatibilidad. Les dejo mi reporte de woocommerce antes del plugin:

`
### WordPress Environment ###

Home URL: https://latamhair.com
Site URL: https://latamhair.com
WC Version: 3.5.4
Log Directory Writable: ✔
WP Version: 5.0.3
WP Multisite: –
WP Memory Limit: ❌ 40 MB - Recomendamos configurar la memoria por lo menos a 64 MB. Ver: Aumentar la memoria asignada para PHP
WP Debug Mode: ✔
WP Cron: ✔
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.0.33-1~dotdeb+8.1 - Recomendamos usar la versión 7.2 o superior de PHP para un mayor rendimiento y seguridad. Cómo actualizar tu versión de PHP
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 
SUHOSIN Installed: –
MySQL Version: ❌ 5.5.62-0+deb8u1 - Recomendamos como versión mínima de MySQL la 5.6. Ver: Requisitos de WordPress
Max Upload Size: 250 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Tu servidor no tiene la clase SoapClient habilitada - puede que algunos plugins de puerta de enlace que utilizan SOAP no funcionen como se espera.
DOMDocument: ✔
GZip: ✔
Multibyte String: ❌ Tu servidor no es compatible con las funciones de mbstring - esto es necesario para una mejor codificación de caracteres. En su lugar
se utilizarán algunos mecanismos alternativos.

Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.4
WC Database Prefix: wp_
Tamaño total de la base de datos: 12.18MB
Tamaño de los datos de la base de datos: 10.88MB
Tamaño del índice de la base de datos: 1.30MB
wp_woocommerce_sessions: Datos: 0.02MB + Índice: 0.02MB
wp_woocommerce_api_keys: Datos: 0.02MB + Índice: 0.03MB
wp_woocommerce_attribute_taxonomies: Datos: 0.02MB + Índice: 0.02MB
wp_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.05MB
wp_woocommerce_order_items: Datos: 0.02MB + Índice: 0.02MB
wp_woocommerce_order_itemmeta: Datos: 0.02MB + Índice: 0.03MB
wp_woocommerce_tax_rates: Datos: 0.02MB + Índice: 0.06MB
wp_woocommerce_tax_rate_locations: Datos: 0.02MB + Índice: 0.03MB
wp_woocommerce_shipping_zones: Datos: 0.02MB + Índice: 0.00MB
wp_woocommerce_shipping_zone_locations: Datos: 0.02MB + Índice: 0.03MB
wp_woocommerce_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB
wp_woocommerce_payment_tokens: Datos: 0.02MB + Índice: 0.02MB
wp_woocommerce_payment_tokenmeta: Datos: 0.02MB + Índice: 0.03MB
wp_woocommerce_log: Datos: 0.02MB + Índice: 0.02MB
wp_aiowps_events: Datos: 0.02MB + Índice: 0.00MB
wp_aiowps_failed_logins: Datos: 1.31MB + Índice: 0.00MB
wp_aiowps_global_meta: Datos: 0.02MB + Índice: 0.00MB
wp_aiowps_login_activity: Datos: 0.02MB + Índice: 0.00MB
wp_aiowps_login_lockdown: Datos: 0.02MB + Índice: 0.00MB
wp_aiowps_permanent_block: Datos: 0.02MB + Índice: 0.00MB
wp_aws_cache: Datos: 0.02MB + Índice: 0.00MB
wp_aws_index: Datos: 0.33MB + Índice: 0.00MB
wp_commentmeta: Datos: 0.13MB + Índice: 0.03MB
wp_comments: Datos: 0.02MB + Índice: 0.09MB
wp_et_social_stats: Datos: 0.02MB + Índice: 0.00MB
wp_links: Datos: 0.02MB + Índice: 0.02MB
wp_options: Datos: 5.02MB + Índice: 0.05MB
wp_postmeta: Datos: 1.48MB + Índice: 0.38MB
wp_posts: Datos: 1.50MB + Índice: 0.13MB
wp_revslider_css: Datos: 0.13MB + Índice: 0.00MB
wp_revslider_layer_animations: Datos: 0.02MB + Índice: 0.00MB
wp_revslider_navigations: Datos: 0.02MB + Índice: 0.00MB
wp_revslider_sliders: Datos: 0.09MB + Índice: 0.00MB
wp_revslider_slides: Datos: 0.17MB + Índice: 0.00MB
wp_revslider_static_slides: Datos: 0.02MB + Índice: 0.00MB
wp_termmeta: Datos: 0.02MB + Índice: 0.03MB
wp_terms: Datos: 0.02MB + Índice: 0.03MB
wp_term_relationships: Datos: 0.02MB + Índice: 0.02MB
wp_term_taxonomy: Datos: 0.02MB + Índice: 0.03MB
wp_usermeta: Datos: 0.02MB + Índice: 0.03MB
wp_users: Datos: 0.02MB + Índice: 0.05MB
wp_wc_download_log: Datos: 0.02MB + Índice: 0.03MB
wp_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB
wp_webpay: Datos: 0.02MB + Índice: 0.00MB
wp_xcloner_scheduler: Datos: 0.02MB + Índice: 0.00MB

### Post Type Counts ###

attachment: 233
custom_css: 2
customize_changeset: 95
et_pb_layout: 6
flamingo_contact: 40
flamingo_inbound: 28
nativo_tutoriales: 1
nav_menu_item: 19
ot_post_service: 6
page: 15
post: 6
product: 51
product_variation: 1
revision: 187
shop_order: 1
testimonial: 2
tutoriales: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (17) ###

Advanced Woo Search: por ILLID – 1.60
Akismet Anti-Spam: por Automattic – 4.1
All In One SEO Pack: por Michael Torbert – 2.10.1
All In One WP Security: por Tips and Tricks HQ
Peter Petreski
Ruhul
Ivy – 4.3.8.3

Autoptimize: por Frank Goossens (futtta) – 2.4.4
Custom Functions Latamhair: por Renan Diaz – 1.0
Editor clásico: por Colaboradores de WordPress – 1.3
Debug Bar: por wordpressdotorg – 1.0
Roles de menú: por Kathy Darling – 1.9.3
Perfect WooCommerce Brands: por Alberto de Vera Sevilla – 1.7.0
PHP Settings: por Askupa Software – 1.0.6
Slider Revolution: por ThemePunch – 5.4.5.1
Upload Max File Size: por Ashutosh Kumar – 1.2
WooCommerce: por Automattic – 3.5.4
WordPress Importer: por wordpressdotorg – 0.6.4
Administrador de archivos WP: por mndpsingh287 – 4.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: CLP ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

### WC Pages ###

Base de la tienda: #1205 - /tienda/
Carrito: #1206 - /cart/
Finalizar compra: #1207 - /checkout/
Mi cuenta: #1208 - /my-account/
Términos y condiciones: ❌ Página sin definir

### Theme ###

Name: Divi Child
Version: 3.19.3.1547044088
Author URL: http://www.elegantthemes.com
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 3.19.3
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: –
`

Saludos!

**Comment by reandimo** [comment]
@goncafa listo amgio ya con soap instalado, me sigue dando error y aumente tambien la memoria de wordpress:

`
### WordPress Environment ###

Home URL: https://latamhair.com
Site URL: https://latamhair.com
WC Version: 3.5.4
Log Directory Writable: ✔
WP Version: 5.0.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.0.33-1~dotdeb+8.1 - Recomendamos usar la versión 7.2 o superior de PHP para un mayor rendimiento y seguridad. Cómo actualizar tu versión de PHP
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 
SUHOSIN Installed: –
MySQL Version: ❌ 5.5.62-0+deb8u1 - Recomendamos como versión mínima de MySQL la 5.6. Ver: Requisitos de WordPress
Max Upload Size: 250 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ❌ Tu servidor no es compatible con las funciones de mbstring - esto es necesario para una mejor codificación de caracteres. En su lugar
se utilizarán algunos mecanismos alternativos.

Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.5.4
WC Database Prefix: wp_
Tamaño total de la base de datos: 12.18MB
Tamaño de los datos de la base de datos: 10.88MB
Tamaño del índice de la base de datos: 1.30MB
wp_woocommerce_sessions: Datos: 0.02MB + Índice: 0.02MB
wp_woocommerce_api_keys: Datos: 0.02MB + Índice: 0.03MB
wp_woocommerce_attribute_taxonomies: Datos: 0.02MB + Índice: 0.02MB
wp_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.05MB
wp_woocommerce_order_items: Datos: 0.02MB + Índice: 0.02MB
wp_woocommerce_order_itemmeta: Datos: 0.02MB + Índice: 0.03MB
wp_woocommerce_tax_rates: Datos: 0.02MB + Índice: 0.06MB
wp_woocommerce_tax_rate_locations: Datos: 0.02MB + Índice: 0.03MB
wp_woocommerce_shipping_zones: Datos: 0.02MB + Índice: 0.00MB
wp_woocommerce_shipping_zone_locations: Datos: 0.02MB + Índice: 0.03MB
wp_woocommerce_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB
wp_woocommerce_payment_tokens: Datos: 0.02MB + Índice: 0.02MB
wp_woocommerce_payment_tokenmeta: Datos: 0.02MB + Índice: 0.03MB
wp_woocommerce_log: Datos: 0.02MB + Índice: 0.02MB
wp_aiowps_events: Datos: 0.02MB + Índice: 0.00MB
wp_aiowps_failed_logins: Datos: 1.31MB + Índice: 0.00MB
wp_aiowps_global_meta: Datos: 0.02MB + Índice: 0.00MB
wp_aiowps_login_activity: Datos: 0.02MB + Índice: 0.00MB
wp_aiowps_login_lockdown: Datos: 0.02MB + Índice: 0.00MB
wp_aiowps_permanent_block: Datos: 0.02MB + Índice: 0.00MB
wp_aws_cache: Datos: 0.02MB + Índice: 0.00MB
wp_aws_index: Datos: 0.33MB + Índice: 0.00MB
wp_commentmeta: Datos: 0.13MB + Índice: 0.03MB
wp_comments: Datos: 0.02MB + Índice: 0.09MB
wp_et_social_stats: Datos: 0.02MB + Índice: 0.00MB
wp_links: Datos: 0.02MB + Índice: 0.02MB
wp_options: Datos: 5.02MB + Índice: 0.05MB
wp_postmeta: Datos: 1.48MB + Índice: 0.38MB
wp_posts: Datos: 1.50MB + Índice: 0.13MB
wp_revslider_css: Datos: 0.13MB + Índice: 0.00MB
wp_revslider_layer_animations: Datos: 0.02MB + Índice: 0.00MB
wp_revslider_navigations: Datos: 0.02MB + Índice: 0.00MB
wp_revslider_sliders: Datos: 0.09MB + Índice: 0.00MB
wp_revslider_slides: Datos: 0.17MB + Índice: 0.00MB
wp_revslider_static_slides: Datos: 0.02MB + Índice: 0.00MB
wp_termmeta: Datos: 0.02MB + Índice: 0.03MB
wp_terms: Datos: 0.02MB + Índice: 0.03MB
wp_term_relationships: Datos: 0.02MB + Índice: 0.02MB
wp_term_taxonomy: Datos: 0.02MB + Índice: 0.03MB
wp_usermeta: Datos: 0.02MB + Índice: 0.03MB
wp_users: Datos: 0.02MB + Índice: 0.05MB
wp_wc_download_log: Datos: 0.02MB + Índice: 0.03MB
wp_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB
wp_webpay: Datos: 0.02MB + Índice: 0.00MB
wp_xcloner_scheduler: Datos: 0.02MB + Índice: 0.00MB

### Post Type Counts ###

attachment: 233
custom_css: 2
customize_changeset: 95
et_pb_layout: 6
flamingo_contact: 40
flamingo_inbound: 28
nativo_tutoriales: 1
nav_menu_item: 19
ot_post_service: 6
page: 15
post: 6
product: 51
product_variation: 1
revision: 187
shop_order: 1
testimonial: 2
tutoriales: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (17) ###

Advanced Woo Search: por ILLID – 1.60
Akismet Anti-Spam: por Automattic – 4.1
All In One SEO Pack: por Michael Torbert – 2.10.1
All In One WP Security: por Tips and Tricks HQ
Peter Petreski
Ruhul
Ivy – 4.3.8.3

Autoptimize: por Frank Goossens (futtta) – 2.4.4
Custom Functions Latamhair: por Renan Diaz – 1.0
Editor clásico: por Colaboradores de WordPress – 1.3
Debug Bar: por wordpressdotorg – 1.0
Roles de menú: por Kathy Darling – 1.9.3
Perfect WooCommerce Brands: por Alberto de Vera Sevilla – 1.7.0
PHP Settings: por Askupa Software – 1.0.6
Slider Revolution: por ThemePunch – 5.4.5.1
Upload Max File Size: por Ashutosh Kumar – 1.2
Transbank Webpay Plus: por Transbank – 2.1.4 – No probado con la versión activa de WooCommerce
WooCommerce: por Automattic – 3.5.4
WordPress Importer: por wordpressdotorg – 0.6.4
Administrador de archivos WP: por mndpsingh287 – 4.0

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: CLP ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)


### WC Pages ###

Base de la tienda: #1205 - /tienda/
Carrito: #1206 - /cart/
Finalizar compra: #1207 - /checkout/
Mi cuenta: #1208 - /my-account/
Términos y condiciones: ❌ Página sin definir

### Theme ###

Name: Divi Child
Version: 3.19.3.1547044088
Author URL: http://www.elegantthemes.com
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 3.19.3
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: –
`

P.D. solo es en la pagina de Ajustes de WooCommerce, todas las demas paginas de WooCommerce funcionan sin problemas hasta donde he visto

**Comment by reandimo** [comment]
Y parece que en el checkout aparece el error 500 :\

**Comment by reandimo** [comment]
No se si sea relevante pero el wordpress esta alojado en una instancia de VM en Google Cloud Platform

**Comment by reandimo** [comment]
por fin logre ver el error y es el siguiente: 

Notice: Undefined index: args in /var/www/html/wp-includes/functions.php on line 5233

Warning: include(/var/www/html/wp-content/plugins/woocommerce-transbank/vendor/composer/../apache/log4php/src/main/php/Logger.php): failed to open stream: No such file or directory in /var/www/html/wp-content/plugins/woocommerce-transbank/vendor/composer/ClassLoader.php on line 444

Notice: Undefined index: args in /var/www/html/wp-includes/functions.php on line 5233

Warning: include(): Failed opening '/var/www/html/wp-content/plugins/woocommerce-transbank/vendor/composer/../apache/log4php/src/main/php/Logger.php' for inclusion (include_path='.:/usr/share/php') in /var/www/html/wp-content/plugins/woocommerce-transbank/vendor/composer/ClassLoader.php on line 444

Fatal error: Uncaught Error: Class 'Logger' not found in /var/www/html/wp-content/plugins/woocommerce-transbank/libwebpay/LogHandler.php:55 Stack trace: #0 /var/www/html/wp-content/plugins/woocommerce-transbank/webpay.php(56): LogHandler->__construct() #1 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(108): WC_Gateway_Transbank->__construct() #2 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(70): WC_Payment_Gateways->init() #3 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(43): WC_Payment_Gateways->__construct() #4 /var/www/html/wp-content/plugins/woocommerce/includes/class-woocommerce.php(690): WC_Payment_Gateways::instance() #5 /var/www/html/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-menus.php(90): WooCommerce->payment_gateways() #6 /var/www/html/wp-includes/class-wp-hook.php(286): WC_Admin_Menus->settings_page_init('') #7 /var/www/html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filter in /var/www/html/wp-content/plugins/woocommerce-transbank/libwebpay/LogHandler.php on line 55

**Comment by reandimo** [comment]
**Resuelto!**

faltaba la libreria mbstring, php-curl en el servidor y luego tuve que reinstalar las librerias necesarias a traves del SSH del servidor con Composer. Luego de eso funciono el plugin!

Para los que hayan tenido el mismo problema que yo asegurense de habilitar la visualizacion de errores en wordpress y tratar de rastrear el error xD

P.D. en mi caso fue por usar Google Cloud Platform ya que hay que instalar algunas cosas manualmente.
